### ISSUE TITLE
GSL download fails while building

### ISSUE THREAD

**Issue by SubhadeepJasu** [flathub/com.github.subhadeepjasu.pebbles#1]
GSL download times out during build.

**Comment by SubhadeepJasu** [comment]
bot, build com.github.SubhadeepJasu.pebbles

**Comment by SubhadeepJasu** [comment]
bot, build

**Comment by danilown** [comment]
Probably some problem with the build server. I'm able to build it locally with no issues.

**Comment by danilown** [comment]
bot, build

**Comment by danilown** [comment]
Yeap, it was just that.
